strictPeerDependencies: true
packages:
  - "packages/docusaurus-search-local"
  - "packages/search-deploy-cli"
  - "packages/cloudflare-worker"

catalog:
  "@docusaurus/core": 3.9.2
  "@docusaurus/module-type-aliases": 3.9.2
  "@docusaurus/plugin-content-blog": 3.9.2
  "@docusaurus/plugin-content-docs": 3.9.2
  "@docusaurus/plugin-content-pages": 3.9.2
  "@docusaurus/types": 3.9.2
  "@docusaurus/utils-validation": 3.9.2
